openshift/cert-manager-operator-release

.gitmodules, Containerfile.cert-manager, Containerfile.cert-manager-operator, Containerfile.cert-manager-operator.bundle, Containerfile.cert-manager.acmesolver, OWNERS, hack/bundle/render_templates.sh
- Add [jetstack-cert-manager](https://github.com/openshift/jetstack-cert-manager) as a git sub-module.
- Add [cert-manager-operator](https://github.com/openshift/cert-manager-operator) as a git sub-module.
- Add Containerfiles for cert-manager, cert-manager-acmesolver, cert-manager-operator, cert-manager-operator-bundle which references code in the respective submodules.
- Values for below ARGs in the Containerfiles will be passed from konflux specific tekton config files
- RELEASE_VERSION: Release version of the operator/operand.
- COMMIT_SHA: Commit which triggered the build in konflux.
- SOURCE_URL: Github repository URL of operator/operand
- CERT_MANAGER_OPERATOR_IMAGE, CERT_MANAGER_WEBHOOK_IMAGE, CERT_MANAGER_CA_INJECTOR_IMAGE, CERT_MANAGER_CONTROLLER_IMAGE, …
=> KONFLUX-191: Initial commit for main branch

.gitmodules, Containerfile.cert-manager, Containerfile.cert-manager-operator, Containerfile.cert-manager-operator.bundle, Containerfile.cert-manager.acmesolver, OWNERS, hack/bundle/render_templates.sh
- Add [jetstack-cert-manager](https://github.com/openshift/jetstack-cert-manager) as a git sub-module.
- Add [cert-manager-operator](https://github.com/openshift/cert-manager-operator) as a git sub-module.
- Add Containerfiles for cert-manager, cert-manager-acmesolver, cert-manager-operator, cert-manager-operator-bundle which references code in the respective submodules.
- Values for below ARGs in the Containerfiles will be passed from konflux specific tekton config files
- RELEASE_VERSION: Release version of the operator/operand.
- COMMIT_SHA: Commit which triggered the build in konflux.
- SOURCE_URL: Github repository URL of operator/operand
- CERT_MANAGER_OPERATOR_IMAGE, CERT_MANAGER_WEBHOOK_IMAGE, CERT_MANAGER_CA_INJECTOR_IMAGE, CERT_MANAGER_CONTROLLER_IMAGE, …
=> KONFLUX-191: Initial commit for release-1.14 branch

.gitmodules, Containerfile.cert-manager, Containerfile.cert-manager-operator, Containerfile.cert-manager-operator.bundle, Containerfile.cert-manager.acmesolver, OWNERS, hack/bundle/render_templates.sh
- Add [jetstack-cert-manager](https://github.com/openshift/jetstack-cert-manager) as a git sub-module.
- Add [cert-manager-operator](https://github.com/openshift/cert-manager-operator) as a git sub-module.
- Add Containerfiles for cert-manager, cert-manager-acmesolver, cert-manager-operator, cert-manager-operator-bundle which references code in the respective submodules.
- Values for below ARGs in the Containerfiles will be passed from konflux specific tekton config files
- RELEASE_VERSION: Release version of the operator/operand.
- COMMIT_SHA: Commit which triggered the build in konflux.
- SOURCE_URL: Github repository URL of operator/operand
- CERT_MANAGER_OPERATOR_IMAGE, CERT_MANAGER_WEBHOOK_IMAGE, CERT_MANAGER_CA_INJECTOR_IMAGE, CERT_MANAGER_CONTROLLER_IMAGE, …
=> KONFLUX-191: Initial commit for release-1.15 branch

renovate.json
We need write access to add labels to PR, hence updating the rebaseLabel in renovate.json to use the `needs-rebase` added by the prow/tide.
=> NO-JIRA: Update rebaseLabel name in renovate config

Makefile, hack/renovate-config-validator.sh, renovate.json
- Updates renovate config with new package managers
- dockerfile
- git-submodules
- New Makefile target for validating renovate config changes.
- New script to validate renovate config.
=> NO-JIRA: Update renovate config with new package managers

Containerfile.cert-manager-operator.bundle
Use images from `registry.stage.redhat.io` for first release of catalog for internal usage.
=> NO-JIRA: Use images from staging server for initial catalog release

.tekton/cert-manager-operator-bundle-1-15-pull-request.yaml, .tekton/cert-manager-operator-bundle-1-15-push.yaml
- CEL validations to avoid redundant builds
- Adds build args
- Enables hermetic build, source build and OCI index
=> NO-JIRA: Customize cert-manager-operator-bundle tekton pac to comply with EC policy

.tekton/jetstack-cert-manager-1-15-pull-request.yaml, .tekton/jetstack-cert-manager-1-15-push.yaml, .tekton/jetstack-cert-manager-acmesolver-1-15-pull-request.yaml, .tekton/jetstack-cert-manager-acmesolver-1-15-push.yaml, catalog/openshift-cert-manager-operator/bundle.yaml
react to changes in https://github.com/openshift/cert-manager-operator/pull/232, update upstream tags.
=> CM-358: [bump/v1.15.4] update operand tags

Containerfile.cert-manager-operator.bundle
Operator(cert-manager-operator) and operand(jetstack-cert-manager, jetstack-cert-manager-acmesolver) image references in the bundle Containerfile are updated, which is updated in bundle CSV manifest during image build.
The image references are updated to recent builds to make a stage release from konflux.
=> NO-JIRA: Update operator and operand image refs in bundle

Containerfile.cert-manager-operator.bundle
cert-manager-operator image references in the bundle Containerfile is updated to the latest, which is updated in bundle CSV manifest during image build.
The image references are updated to recent builds to make a stage release from konflux.
=> NO-JIRA: Update cert-manager-operator image ref in bundle

Containerfile.cert-manager-operator.bundle, hack/bundle/render_templates.sh
Follow-up over https://github.com/openshift/cert-manager-operator/pull/221, ref: #95
=> CM-436: Cleanup kube-rbac-proxy

Containerfile.cert-manager-operator.bundle
PR is for updating the image reference in the bundle Containerfile with the GA images, which will be used for updating the images referenced in operator manifest during bundle image build.
=> CM-373: Update image references in operator bundle manifest

.tekton/fbc-build-pipeline.yaml, .tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
EC policy validation is failing with `CycloneDX SBOM` invalid error, which is happening because of CycloneDX version bump from 1.5 to 1.6.
Updating the konflux task image references, since automated update will happen later this week, and this s required for 1.15 release.
=> NO-JIRA: konflux team fix for false sbom_cyclonedx EC violation

.tekton/single-arch-build-pipeline.yaml, Containerfile.cert-manager-operator.bundle, hack/bundle/render_templates.sh
PR has below changes:
- Updates bundle Containerfile to add istio-csr image ref, which will be used to replace the default image in bundle CSV manifest during build.
- Updates template CSV manifest rendering script to replace istio-csr image in the manifest, which is required for deploying istio-csr with the required image.
=> CM-464: Adds istio-csr image ref in bundle CSV

Containerfile.cert-manager-operator.bundle
PR is for updating container images references to latest in the bundle, which when building the bundle images updates the references in the operator manifest.
=> CM-464: Update container images references to latest in the bundle

catalogs/v4.18/catalog/openshift-cert-manager-operator/bundle-v1.15.1.yaml, catalogs/v4.19/catalog/openshift-cert-manager-operator/bundle-v1.15.1.yaml
PR is for updating 4.18 and 4.19 operator catalog with latest 1.15.1 bundle.
=> CM-464: Updates 4.18, 4.19 catalogs with latest 1.15.1 bundle

.tekton/fbc-build-pipeline.yaml, .tekton/images-mirror-set.yaml
All products building FBC fragments in Konflux are requested to merge this change irrespective of whether the product is intended for FIPS mode or not.
Beginning March 1, 2025, the fbc-fips-task is going to be a required task in the Konflux
pipeline. This means, your release will be blocked if this task is not present in your pipeline run.
The answer is yes. If your product is not designed to operate in FIPS mode, the task will identify that and will
automatically skip the FIPS scan. However, the task still needs to be a part of your pipeline.
* This commit adds the fbc-fips-check task to your pipeline yaml.
* It also adds a file named `images-mirror-set.yaml` to your `.tekton` directory with an example in it. This file is an `ImageDigestMirrorSet` required by the task to access any …
=> NO-JIRA: RELEASE BLOCKER(March 1, 2025): add fbc-fips-check task to FBC pipeline

.tekton/fbc-build-pipeline.yaml, .tekton/images-mirror-set.yaml
All products building FBC fragments in Konflux are requested to merge this change irrespective of whether the product is intended for FIPS mode or not.
Beginning March 1, 2025, the fbc-fips-task is going to be a required task in the Konflux
pipeline. This means, your release will be blocked if this task is not present in your pipeline run.
The answer is yes. If your product is not designed to operate in FIPS mode, the task will identify that and will
automatically skip the FIPS scan. However, the task still needs to be a part of your pipeline.
* This commit adds the fbc-fips-check task to your pipeline yaml.
* It also adds a file named `images-mirror-set.yaml` to your `.tekton` directory with an example in it. This file is an `ImageDigestMirrorSet` required by the task to access any …
=> NO-JIRA: RELEASE BLOCKER(March 1, 2025): adds fbc-fips-check task to FBC pipeline

.tekton/cert-manager-istio-csr-1-15-pull-request.yaml, .tekton/cert-manager-istio-csr-1-15-push.yaml, Containerfile.cert-manager-istio-csr
PR has following changes:
- Updates istio-csr version to 0.14.0 in image build args passed in tekton pac.
- Update cert-manager operator & istio-csr submodules to latest commits containing the istio-csr bump to 0.14.0 from 0.12.0 and featuregate changes in cert-manager-operator for istio-csr feature.
- Updates the base image `brew.registry.redhat.io/rh-osbs/openshift-golang-builder` in istio-csr Containerfile to `rhel_9_golang_1.23`, required after bump to 0.14.0
=> CM-464: Updates submodules to latest commits and istio-csr version to 0.14.0 in image build args

.tekton/single-arch-build-pipeline.yaml
`ecosystem-cert-preflight-checks` are skipped for operator bundles, and the EC policy validation fails when any task is skipped. And as per the [suggestion](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1741013604727269?thread_ts=1740901637.372379&cid=C04PZ7H0VA8) from konflux team, removing non-essential task from the pipeline.
Task logs:
```
step-set-skip-for-bundles
{"result":"SKIPPED","timestamp":"2025-03-12T13:54:51+00:00","note":"This ecosystem check is not executed for operatorbundles.","namespace":"default","successes":0,"failures":0,"warnings":0}
```
EC policy verification logs:
```
"violations": [
{
"msg": "The Task \"ecosystem-cert-preflight-checks\" from the build Pipeline reports a test was skipped",
"metadata": {
"code": "test.no_skipped_tests",
"collections": [ …
```
=> CM-464: Remove ecosystem-cert-preflight-checks task from tekton pipeline for bundle

Containerfile.cert-manager-operator.bundle
Update bundle refs with staging SHAs with latest jetstack-cert-manager-stanging-1-14 refs built from `jetstack-cert-manager-1-14-2g9rv` snapshot.
Staging Release: https://console-openshift-console.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/k8s/ns/cert-manager-oape-tenant/appstudio.redhat.com~v1alpha1~Release/jetstack-cert-manager-1-14-2g9rv-d9c4cbe-7hmcx/yaml
=> [release-1.14] CM-458: Update bundle refs with staging SHAs

Containerfile.cert-manager-operator.bundle
Update bundle refs with staging SHAs with latest cert-manager-operator-1-14 refs built from cert-manager-operator-1-14-only-operator-dslr6 snapshot.
Staging Release: https://console-openshift-console.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/k8s/ns/cert-manager-oape-tenant/appstudio.redhat.com~v1alpha1~Release/cert-manager-operator-staging-1-14g5djn/yaml
=> CM-458: Update bundle refs with latest cert-manager-operator staging SHAs

go.mod, go.sum, renovate.json
PR has below changes
- Updates below go modules
- github.com/elliotchance/orderedmap v1.7.1
golang.org/x/sys v0.32.0
golang.org/x/text v0.24.0
- Disables renovate-bot from creating PRs with go module updates, since the modules here are used for building yq tool, which is not part of release payload and is not critical to stay updated.
=> [release-1.15] NO-JIRA: Updates go modules to latest and disables renovatebot from updating modules

hack/update_catalog.sh
Bundle images created must not be multi-arch and must not be indexed too, when building catalog images through konflux. And for the catalog to function correctly in a multi-arch scenario, the referenced bundle digests must point to the correct type. They must not be `application/vnd.docker.distribution.manifest.list.v2+json`, but must be of `application/vnd.oci.image.manifest.v1+json` or `application/vnd.docker.distribution.manifest.v2+json` types.
References:
- https://konflux.pages.redhat.com/docs/users/getting-started/building-olm-products.html#building-bundle-images
- https://konflux.pages.redhat.com/docs/users/getting-started/building-olm-products.html#building-file-based-catalog-fbc-components:~:text=Bundle%20images%20SHOULD%20NOT%20be%20referenced,Index%20or%20manifest%20list%20is%2 …
=> CM-556: Verify bundle image before updating fbc

.tekton/single-arch-build-pipeline.yaml
Following thread https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1744720525525849?thread_ts=1744715688.629639&cid=C04PZ7H0VA8
Konflux doc ref: https://konflux.pages.redhat.com/docs/users/getting-started/building-olm-products.html#building-file-based-catalog-fbc-components:~:text=Bundle%20images%20SHOULD%20NOT%20be%20referenced,Index%20or%20manifest%20list%20is%20encountered
=> [release-1.14] NO-JIRA: override 'build-image-index' to false for single-arch-build-pipeline

.tekton/single-arch-build-pipeline.yaml
Following thread https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1744720525525849?thread_ts=1744715688.629639&cid=C04PZ7H0VA8
Konflux doc ref: https://konflux.pages.redhat.com/docs/users/getting-started/building-olm-products.html#building-file-based-catalog-fbc-components:~:text=Bundle%20images%20SHOULD%20NOT%20be%20referenced,Index%20or%20manifest%20list%20is%20encountered
=> [release-1.15] NO-JIRA: override 'build-image-index' to false for single-arch-build-pipeline

.tekton/cert-manager-operator-fbc-push.yaml
[Open to discussion] Experimentally use deterministic tag for FBC image. This may eliminate the error-prone and redundant process to retrieve the latest catalog build for testing.
=> NO-JIRA: change to use deterministic tag for catalog image

.tekton/cert-manager-istio-csr-1-15-pull-request.yaml, .tekton/cert-manager-istio-csr-1-15-push.yaml, .tekton/cert-manager-operator-bundle-1-15-pull-request.yaml, .tekton/cert-manager-operator-bundle-1-15-push.yaml, .tekton/single-arch-build-pipeline.yaml
This PR changes Service Account used by build pipeline from "appstudio-pipeline" to dedicated to the Component Service Account.
This PR is the changes created by bot in https://github.com/openshift/cert-manager-operator-release/pull/368 https://github.com/openshift/cert-manager-operator-release/pull/364 where the builds are failing since the PRs are not getting rebased.
=> [release-1.15] NO-JIRA: Konflux build pipeline service account migration to use components own

.tekton/cert-manager-operator-1-14-pull-request.yaml, .tekton/cert-manager-operator-1-14-push.yaml, .tekton/cert-manager-operator-bundle-1-14-pull-request.yaml, .tekton/cert-manager-operator-bundle-1-14-push.yaml, .tekton/jetstack-cert-manager-1-14-pull-request.yaml, .tekton/jetstack-cert-manager-1-14-push.yaml, .tekton/single-arch-build-pipeline.yaml
This PR changes Service Account used by build pipeline from "appstudio-pipeline" to dedicated to the Component Service Account.
This PR is the changes created by bot in https://github.com/openshift/cert-manager-operator-release/pull/378 https://github.com/openshift/cert-manager-operator-release/pull/376 https://github.com/openshift/cert-manager-operator-release/pull/367 https://github.com/openshift/cert-manager-operator-release/pull/365 where the builds are failing since the PRs are not getting rebased.
=> [release-1.14] NO-JIRA: Konflux build pipeline service account migration to use components own

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
Pull changes from release-1.15 branch for `.tekton/*-arch-build-pipeline.yaml` to fix failing enterprise contract on stage release.
=> [release-1.16] CM-532: Sync build-pipeline(s) with release-1.15 branch

Containerfile.cert-manager-operator.bundle
Update bundle with latest stage release:
- https://catalog.stage.redhat.com/software/containers/cert-manager/cert-manager-operator-rhel9/63d34c7870c621093f318724 (release/cert-manager-operator-1-16-zlgn8-16a71e7-2jm5l)
=> [release-1.16] CM-532: Update operator image with latest stage build

Containerfile.cert-manager-operator.bundle
Update 1.16.1 prod build image sha256 references , based on the following build artifacts
- https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/cert-manager-oape-tenant/applications/jetstack-cert-manager-1-16/releases/jetstack-cert-manager-prod-1-166ctns
- https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/cert-manager-oape-tenant/applications/cert-manager-operator-1-16/releases/cert-manager-operator-prod-1-16t4fzx/
Tested with image pull
```sh
podman pull registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:831e4b1e5aa6eed6fbb22f779ddbcb9c73e4bf6cc079d0c6652737a6a44e6320
Trying to pull registry.redhat.io/cert-manager/jetstack-cert-manager-acmesolver-rhel9@sha256:831e4b1e5aa6eed6fbb22f779ddbcb9c73e4bf6cc079d0c6652737a6a44e6320... …
```
=> CM-613: Upgrade 1.16.1 staging builds to GA

Containerfile.cert-manager-operator.bundle
Update 1.17.0 staging build image sha256 references, based on the following staging build artifacts
- https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/cert-manager-oape-tenant/applications/cert-manager-operator-1-17/releases/cert-manager-operator-1-17-slv5t-456c52a-p6xqq
- https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/cert-manager-oape-tenant/applications/jetstack-cert-manager-1-17/releases/jetstack-cert-manager-1-17-cxns4-456c52a-8cxch
Tested with image pull
```sh
> podman pull registry.stage.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:4d5e238300ce6f427a1045d51d6b37a4e5c5633985208ebb44f91e7dd53897d9
Trying to pull registry.stage.redhat.io/cert-manager/cert-manager-operator-rhel9@sha256:4d5e238300ce6f427a1045d51d6b37a4e5c5633985208ebb4 …
```
=> CM-585: [release-1.17] Update 1.17.0 staging build image sha256 reference

catalogs/v4.14/catalog/openshift-cert-manager-operator/channel.yaml, catalogs/v4.15/catalog/openshift-cert-manager-operator/channel.yaml, catalogs/v4.16/catalog/openshift-cert-manager-operator/channel.yaml, catalogs/v4.17/catalog/openshift-cert-manager-operator/channel.yaml, catalogs/v4.18/catalog/openshift-cert-manager-operator/channel.yaml, catalogs/v4.19/catalog/openshift-cert-manager-operator/channel.yaml
Update channel entries for all OCP index (v4.14-v4.19) having support for `v1.16.0` in `stable-v1`, `stable-v1.16`, `stable-v1.17` (if has) channels. 
And we would need to re-release FBCs for all supported OCP versions (v4.14-v4.19).
```yaml
- name: cert-manager-operator.v1.16.1
replaces: cert-manager-operator.v1.15.1
skipRange: '>=1.15.1 <1.16.1'
skips: 
- cert-manager-operator.v1.16.0
```
See the following Slack threads for more details:
- https://redhat-internal.slack.com/archives/C3VS0LV41/p1755073224707029
- https://redhat-internal.slack.com/archives/C045Y7FL3A6/p1754980744497329
/cc @bharath-b-rh @lunarwhite
=> OCPBUGS-60289: Fix upgrade path for v1.15.0->v1.15.1->v1.16.1

Containerfile.cert-manager-operator.bundle
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> KONFLUX-6210: chore: fix and set name and cpe label for cert-manager-operator-bundle-1-16

Containerfile.cert-manager-operator
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> KONFLUX-6210: chore: fix and set name and cpe label for cert-manager-operator-1-16

Containerfile.cert-manager.acmesolver
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> KONFLUX-6210: chore: fix and set name and cpe label for jetstack-cert-manager-acmesolver-1-17

Containerfile.cert-manager
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> KONFLUX-6210: chore: fix and set name and cpe label for jetstack-cert-manager-1-17
