openshift/cert-manager-operator-release

Containerfile.cert-manager, Containerfile.cert-manager-operator, Containerfile.cert-manager-operator.bundle, Containerfile.cert-manager.acmesolver, Makefile, README.md, docs/development/konflux.md
PR contain below changes
- Updated image references to latest version.
- Updated `cert-manager-operator` sub module to latest. 
- Added Makefile.
=> [release-1.14] CM-359: Update submodules and image references

Containerfile.cert-manager, Containerfile.cert-manager-operator, Containerfile.cert-manager-operator.bundle, Containerfile.cert-manager.acmesolver, Makefile, README.md, docs/development/konflux.md
PR contain below changes
- Updated image references to latest version.
- Updated cert-manager-operator sub module to latest.
- Added Makefile.
=> [release-1.15] CM-359: Update submodules and image references

Containerfile.cert-manager, Containerfile.cert-manager-operator, Containerfile.cert-manager-operator.bundle, Containerfile.cert-manager.acmesolver, Makefile, README.md, docs/development/konflux.md
PR contain below changes
- Updated image references to latest version.
- Updated cert-manager-operator sub module to latest.
- Added Makefile.
=> CM-359: Update submodules and image references

Makefile, hack/bundle/render_templates.sh, hack/containerfile-linter.sh, hack/shell-scripts-linter.sh, renovate.json
PR has below changes
- Replaced hardcodings with variable substitution
- Pass args during image build
- Updates default container engine to podman
- Adds `verify` target
- Adds new scripts for verifying shell scripts and containerfiles.
- Add renovate config for automerging PRs created by konfluxbot.
=> KONFLUX-191: Add renovate config for automerging konfluxbot PRs

.gitmodules, Containerfile.cert-manager-istio-csr, Containerfile.istio-csr, Makefile, README.md, hack/containerfile-linter.sh, hack/shell-scripts-linter.sh
- Added submodule for [istio-csr](https://github.com/openshift/cert-manager-istio-csr)
- Added containerfile for istio-csr
=> CM-414: Created Containerfile for istio-csr with redhat base image.

.tekton/cert-manager-operator-1-15-pull-request.yaml, .tekton/cert-manager-operator-1-15-push.yaml, .tekton/cert-manager-operator-bundle-1-15-pull-request.yaml, .tekton/cert-manager-operator-bundle-1-15-push.yaml
Konflux bot is not updating the customized pipeline code with new available task definitions and requires reconfiguring customization, will check more with the konflux team.
=> NO-JIRA: tekton pac customizations after pipeline tasks update

.gitignore, .tekton/cert-manager-operator-1-14-pull-request.yaml, .tekton/cert-manager-operator-1-14-push.yaml, .tekton/cert-manager-operator-bundle-1-14-pull-request.yaml, .tekton/cert-manager-operator-bundle-1-14-push.yaml, .tekton/cert-manager-operator-fbc-1-14-pull-request.yaml, .tekton/cert-manager-operator-fbc-1-14-push.yaml, .tekton/jetstack-cert-manager-1-14-pull-request.yaml, .tekton/jetstack-cert-manager-1-14-push.yaml, .tekton/jetstack-cert-manager-acmesolver-1-14-pull-request.yaml, .tekton/jetstack-cert-manager-acmesolver-1-14-push.yaml, Makefile, hack/containerfile-linter.sh, hack/renovate-config-validator.sh, renovate.json
PR has following changes:
- Sync common changes from release-1.15 branch like Makefile, renovate config, hack scripts..
- Updates the tekton pipeline code with customization to avoid redundant builds, multi platforms config.
=> NO-JIRA: Sync changes from release-1.15 branch

.tekton/cert-manager-istio-csr-1-15-pull-request.yaml, .tekton/cert-manager-istio-csr-1-15-push.yaml, .tekton/cert-manager-operator-1-15-pull-request.yaml
This PR updates the tekton pipeline config code for cert-manager-istio-csr files.
cc: @bharath-b-rh
=> CM-417: Update tekton pipeline config code for istio-csr

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
PR is for updating the konflux build pipelines to latest where task image digests, tasks names and tasks params have been updated, which is required for the builds to go through.
=> NO-JIRA: Updates konflux pipeline build definitions to latest

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
PR has changes for updating the tekton configs code. Latest build pipeline definitions have changes to the tasks, where the tasks definitions have been modified and few have been removed. These changes are required since builds are failing with `tampered code` error.
=> NO-JIRA: Updates tekton configs code with new tasks

.tekton/cert-manager-istio-csr-1-15-pull-request.yaml, .tekton/cert-manager-istio-csr-1-15-push.yaml, Containerfile.cert-manager-istio-csr
PR is for updating the label values in istio-csr Containerfile and indentation correction in istio-csr tekton pac.
=> NO-JIRA: Updates labels in istio-csr Containerfile and indentation in tekton pac

catalogs/v4.18/catalog/openshift-cert-manager-operator/bundle-v1.15.1.yaml, catalogs/v4.18/catalog/openshift-cert-manager-operator/channel.yaml, catalogs/v4.19/catalog/openshift-cert-manager-operator/bundle-v1.15.1.yaml, catalogs/v4.19/catalog/openshift-cert-manager-operator/channel.yaml
- PR is for updating 4.18 and 4.19 operator catalog with 1.15.1 bundle and channel for stage release.
- Since its stage release just the 4.18 and 4.19 catalogs are updated.
=> CM-464: Updates 4.18, 4.19 catalogs with 1.15.1 bundle

Containerfile.cert-manager-operator.bundle, hack/bundle/render_templates.sh, hack/update_catalog.sh
Manual cherry-pick of https://github.com/openshift/cert-manager-operator-release/pull/100
=> [release-1.14] CM-470: Cleanup kube-rbac-proxy

.tekton/fbc-build-pipeline.yaml, .tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
PR contains below changes:
- Updates the tekton pipeline code definitions to the latest.
- Updates cert-manager-operator submodule to the latest commit.
=> NO-JIRA: Updates tekton pipeline code and submodules to latest commit

Containerfile.cert-manager-operator.bundle
PR is for updating container images references to the latest prod builds in the bundle, which when building the bundle images updates the references in the operator manifest.
=> CM-464: Updates latest prod container images references in the bundle

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
Updates tekton pipeline config code to latest for multi and single arch pipeline builds.
=> CM-484: Updates pipeline definitions for multi and single arch builds

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
PR is for updating the konflux pipeline definitions which has new tasks and is required for PRs with `Konflux build pipeline service account migration` to go through and also for any new builds to go through.
=> NO-JIRA: Update konflux pipeline definitions

.tekton/multi-arch-build-pipeline.yaml, .tekton/single-arch-build-pipeline.yaml
Manual cherrypick of https://github.com/openshift/cert-manager-operator-release/pull/383
=> [release-1.14] NO-JIRA: Update konflux pipeline definitions

.tekton/cert-manager-istio-csr-1-16-pull-request.yaml, .tekton/cert-manager-istio-csr-1-16-push.yaml, .tekton/cert-manager-operator-1-16-pull-request.yaml, .tekton/cert-manager-operator-1-16-push.yaml, .tekton/cert-manager-operator-bundle-1-16-pull-request.yaml, .tekton/cert-manager-operator-bundle-1-16-push.yaml, .tekton/jetstack-cert-manager-1-16-pull-request.yaml, .tekton/jetstack-cert-manager-1-16-push.yaml, .tekton/jetstack-cert-manager-acmesolver-1-16-pull-request.yaml, .tekton/jetstack-cert-manager-acmesolver-1-16-push.yaml, hack/tkn_expr_patch_yq.py
Follow-up over #413 per https://github.com/openshift/cert-manager-operator-release/pull/413#discussion_r2088520170, which was/is present in release-1.15 too.
=> [release-1.16] NO-JIRA: Update configs to trigger pipelines on selective paths

renovate.json
Updates operator submodule with https://github.com/openshift/cert-manager-operator/commit/6bf049282a93fdb7e784049f9361cdec65e10e13 and enables renovate bot to auto send future PRs for such updates.
=> [release-1.16] CM-532: Update submodules
